/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package factorio.train.analyser;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void appHasAGreeting() {
        App classUnderTest = new App(null);
        //assertNotNull("app should have a greeting", classUnderTest.decode());
    }
}
