/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package factorio.train.analyser;

import java.util.ArrayList;

import factorio.train.analyser.analyser.Deadlock_Analyser;
import factorio.train.analyser.analyser.Result;
import factorio.train.analyser.decoder.Decoder;
import factorio.train.analyser.graph.Graph;
import factorio.train.analyser.graph.Node;
import factorio.train.analyser.graph.Section;
import factorio.train.analyser.graph.Track;
import factorio.train.analyser.jsonmodels.Entity;
import factorio.train.analyser.jsonmodels.Position;

public class App {

    private static final String blueprint = "0eNqdl9tuwjAMht/F1wWRQ5umrzJNU4EIIkFAbZmGUN99BTZGhRm2L4uSDx9/OyeYbw5h38TUQXWCuNilFqq3E7RxlerN+bfuuA9QQezCFjJI9fb81dRxA30GMS3DF1Sqf88gpC52MVzvXz6OH+mwnYdmOHC72XbD3dW6m1wQGex37XBrl85/NZCsGY4eoZoo7fo+ewBpOsj9CzIjXyaLdR3T5MfrR5j20/wXl09zDGjHwOeo8g9lB1QGy9iExfWIRsC5IHaohQXLZWOZdjpBalA7S56dnmmnJybKlOOcj8AWAasZOQL6FgHz2mBF7x7tOVwtqCyDZUwZEem1hZbONRwuo6dyDrcQ9AAeUScivbawpHNZteTJXMupAD0TVJZCJ4cSRBQnaensUB6fHVrQP8qjJMv38gkp58lwOfbypVrqgq+WyhEqxvHVksQtBTmicL2Ii600M75aUiw0iq+WJK5gmSNxjYiLkSxfLUkW5ny1JHF5K97dKqoeNpwC4zvqknuneRbXPCPpJ5zkpYstzWs7E9QT/kZQYk21FE21mrrbem4MJBMK3WysZEINpOGFeXmDVndP1gw+Q9Ne26FU1nntSutN4Yu+/wY1Fsl8";

    public String decode() {
        Matrix matrix = new Matrix(blueprint);
        Graph graph = new Graph(blueprint);
        graph.getClass();
        Decoder decoder = new Decoder();
        String decodedString = decoder.decode(blueprint);
        Deadlock_Analyser analyser = new Deadlock_Analyser(graph);
        ArrayList<Result> result = analyser.deadlockCheck();
        return (decodedString + "\n" + matrix);
        //Matrix matrix_copy = matrix;
        //return deadlockmatrix(matrix_copy, result);
    }
/*
    private String deadlockmatrix(Matrix matrix_blueprint, ArrayList<ArrayList<Section>> deadlocks) {
        String result = "";
        for (ArrayList<Section> deadlock : deadlocks) {
            if (deadlock.size() > 1) {
                ArrayList<Position> positions = new ArrayList<Position>();
                for (Section section : deadlock) {
                    for (Node node : section.getNodes()) {
                        for (Track track : node.getTracks()) {
                            positions.add(track.getPosition());
                        }
                    }

                }
                ArrayList<Entity>[][] matrix_entities = matrix_blueprint.getMatrix();
                for (ArrayList<Entity>[] arrayLists : matrix_entities) {
                    for (ArrayList<Entity> arrayList : arrayLists) {
                        if (arrayList != null) {
                            for (int i = 0; i < arrayList.size(); i++) {
                                for (int j = 0; j < positions.size(); j++) {
                                    if (arrayList.get(i).getPosition().getX() == positions.get(j).getX()
                                            && arrayList.get(i).getPosition().getY() == positions.get(j).getY()) {
                                        continue;
                                    } else if (j == positions.size() - 1
                                            && !(arrayList.get(i).getPosition().getX() == positions.get(j).getX())) {
                                        arrayList.remove(i);
                                    }
                                }
                            }
                        }
                    }
                }
                Matrix deadlockMatrix = new Matrix();
                deadlockMatrix.overrideMatrix(matrix_entities);
                System.out.println("\n" + "------" + "\n" + deadlockMatrix.toString());
            } else {
                System.out.println("\n" + "------" + "\n" + "no deadlock");
            }
        }
        return result;
    }
*/
    public static void main(String[] args) {
        System.out.println(new App().decode());
    }
}
